package stockinn;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    Color DefaultColor,ClickedColor;
    public Dashboard() {
        initComponents();
        DefaultColor=new Color(242,242,242);
        ClickedColor=new Color(204,204,204);
        
        products_pannel.setBackground(DefaultColor);
        products_detail_pannel.setBackground(DefaultColor);
        Suppliers_pannel.setBackground(DefaultColor);
        Sales_pannel.setBackground(DefaultColor);

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        name_panel = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        products_pannel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        products_detail_pannel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Suppliers_pannel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Sales_pannel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        logout_pannel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        name_panel.setBackground(new java.awt.Color(0, 0, 0));
        name_panel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        name_panel.setForeground(new java.awt.Color(255, 255, 255));
        name_panel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_panel.setText("   GODAM-(IMS)");
        name_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        name_panel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        name_panel.setOpaque(true);

        name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name.setText("Products Menu :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(name_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(name)
                .addGap(384, 384, 384))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(name_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(name)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 110));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        products_pannel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        products_pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                products_pannelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                products_pannelMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/prduct.png"))); // NOI18N
        jLabel1.setText("ADD Products ");

        javax.swing.GroupLayout products_pannelLayout = new javax.swing.GroupLayout(products_pannel);
        products_pannel.setLayout(products_pannelLayout);
        products_pannelLayout.setHorizontalGroup(
            products_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(products_pannelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        products_pannelLayout.setVerticalGroup(
            products_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(products_pannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        products_detail_pannel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        products_detail_pannel.setPreferredSize(new java.awt.Dimension(160, 62));
        products_detail_pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                products_detail_pannelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                products_detail_pannelMousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/detail.png"))); // NOI18N
        jLabel2.setText("Product Details");

        javax.swing.GroupLayout products_detail_pannelLayout = new javax.swing.GroupLayout(products_detail_pannel);
        products_detail_pannel.setLayout(products_detail_pannelLayout);
        products_detail_pannelLayout.setHorizontalGroup(
            products_detail_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, products_detail_pannelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        products_detail_pannelLayout.setVerticalGroup(
            products_detail_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        Suppliers_pannel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Suppliers_pannel.setPreferredSize(new java.awt.Dimension(160, 62));
        Suppliers_pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Suppliers_pannelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Suppliers_pannelMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/supplier.png"))); // NOI18N
        jLabel3.setText("Suppliers");

        javax.swing.GroupLayout Suppliers_pannelLayout = new javax.swing.GroupLayout(Suppliers_pannel);
        Suppliers_pannel.setLayout(Suppliers_pannelLayout);
        Suppliers_pannelLayout.setHorizontalGroup(
            Suppliers_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Suppliers_pannelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Suppliers_pannelLayout.setVerticalGroup(
            Suppliers_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Suppliers_pannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Sales_pannel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sales_pannel.setPreferredSize(new java.awt.Dimension(160, 62));
        Sales_pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sales_pannelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Sales_pannelMousePressed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sales.png"))); // NOI18N
        jLabel4.setText("Sales");

        javax.swing.GroupLayout Sales_pannelLayout = new javax.swing.GroupLayout(Sales_pannel);
        Sales_pannel.setLayout(Sales_pannelLayout);
        Sales_pannelLayout.setHorizontalGroup(
            Sales_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Sales_pannelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        Sales_pannelLayout.setVerticalGroup(
            Sales_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sales_pannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        logout_pannel.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        logout_pannel.setPreferredSize(new java.awt.Dimension(162, 40));
        logout_pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_pannelMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        jLabel5.setText("Log Out");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout logout_pannelLayout = new javax.swing.GroupLayout(logout_pannel);
        logout_pannel.setLayout(logout_pannelLayout);
        logout_pannelLayout.setHorizontalGroup(
            logout_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logout_pannelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        logout_pannelLayout.setVerticalGroup(
            logout_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logout_pannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(products_pannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(products_detail_pannel, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
            .addComponent(Suppliers_pannel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
            .addComponent(Sales_pannel, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout_pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(products_pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(products_detail_pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Suppliers_pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Sales_pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(logout_pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 111, 210, 460));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 730, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout_pannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_pannelMouseClicked
        // TODO add your handling code here:
    int response = JOptionPane.showConfirmDialog(
        this, 
        "Are you sure you want to logout?", 
        "Logout", 
        JOptionPane.YES_NO_OPTION
    );
    
    if (response == JOptionPane.YES_OPTION) {
        new Login().setVisible(true); // Assuming you have a Login form to show after logout
        this.dispose();
    }
    }//GEN-LAST:event_logout_pannelMouseClicked

    private void products_pannelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_products_pannelMousePressed
        // TODO add your handling code here:
        products_pannel.setBackground(ClickedColor);
        products_detail_pannel.setBackground(DefaultColor);
        Suppliers_pannel.setBackground(DefaultColor);
        Sales_pannel.setBackground(DefaultColor);
        
        name.setText("Products Menu:");
        
    }//GEN-LAST:event_products_pannelMousePressed

    private void products_detail_pannelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_products_detail_pannelMousePressed
        // TODO add your handling code here:
        products_pannel.setBackground(DefaultColor);
        products_detail_pannel.setBackground(ClickedColor);
        Suppliers_pannel.setBackground(DefaultColor);
        Sales_pannel.setBackground(DefaultColor);
        
        name.setText("Products Detail Menu:");
    }//GEN-LAST:event_products_detail_pannelMousePressed

    private void Suppliers_pannelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Suppliers_pannelMousePressed
        // TODO add your handling code here:
        products_pannel.setBackground(DefaultColor);
        products_detail_pannel.setBackground(DefaultColor);
        Suppliers_pannel.setBackground(ClickedColor);
        Sales_pannel.setBackground(DefaultColor);
        
         name.setText("Suppliers Menu:");
    }//GEN-LAST:event_Suppliers_pannelMousePressed

    private void Sales_pannelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sales_pannelMousePressed
        // TODO add your handling code here:
        products_pannel.setBackground(DefaultColor);
        products_detail_pannel.setBackground(DefaultColor);
        Suppliers_pannel.setBackground(DefaultColor);
        Sales_pannel.setBackground(ClickedColor);
        
         name.setText("Sales Menu:");
    }//GEN-LAST:event_Sales_pannelMousePressed

    private void products_pannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_products_pannelMouseClicked
        // TODO add your handling code here:
        products p1=new products();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(p1).setVisible(true);
    }//GEN-LAST:event_products_pannelMouseClicked

    private void products_detail_pannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_products_detail_pannelMouseClicked
        // TODO add your handling code here:
        product_details pd1= new product_details();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(pd1).setVisible(true);
    }//GEN-LAST:event_products_detail_pannelMouseClicked

    private void Suppliers_pannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Suppliers_pannelMouseClicked
        // TODO add your handling code here:
        suppliers sup= new suppliers();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(sup).setVisible(true);
    }//GEN-LAST:event_Suppliers_pannelMouseClicked

    private void Sales_pannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sales_pannelMouseClicked
        // TODO add your handling code here:
        sales s1= new sales();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(s1).setVisible(true);
    }//GEN-LAST:event_Sales_pannelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Sales_pannel;
    private javax.swing.JPanel Suppliers_pannel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel logout_pannel;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name_panel;
    private javax.swing.JPanel products_detail_pannel;
    private javax.swing.JPanel products_pannel;
    // End of variables declaration//GEN-END:variables
}
