
package stockinn;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author pc
 */
public class products extends javax.swing.JInternalFrame {

    /**
     * Creates new form products
     */
    public products() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane (null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        FullPannel = new javax.swing.JPanel();
        pname_label = new javax.swing.JLabel();
        quantity_label = new javax.swing.JLabel();
        pcode_label = new javax.swing.JLabel();
        ratePerUnit = new javax.swing.JLabel();
        productcode_text = new javax.swing.JTextField();
        productname_text = new javax.swing.JTextField();
        qunatity_text = new javax.swing.JTextField();
        ratePerUnit_text = new javax.swing.JTextField();
        Spannel = new javax.swing.JPanel();
        sType = new javax.swing.JLabel();
        type_combo = new javax.swing.JComboBox<>();
        SInfo_label = new javax.swing.JLabel();
        sName_label = new javax.swing.JLabel();
        SupName_text = new javax.swing.JTextField();
        supEmailText = new javax.swing.JTextField();
        SupContact_text = new javax.swing.JTextField();
        sEmail_label = new javax.swing.JLabel();
        sContact_label = new javax.swing.JLabel();
        remove_button = new javax.swing.JButton();
        add_button = new javax.swing.JButton();

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FullPannel.setBackground(new java.awt.Color(204, 204, 204));

        pname_label.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        pname_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pname_label.setText("Product Name :");
        pname_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        quantity_label.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        quantity_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantity_label.setText("Quantity :");
        quantity_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        pcode_label.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        pcode_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pcode_label.setText("Product Code :");
        pcode_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        ratePerUnit.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        ratePerUnit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ratePerUnit.setText("Rate per unit :");
        ratePerUnit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        productcode_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        productname_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        qunatity_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        qunatity_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qunatity_textActionPerformed(evt);
            }
        });

        ratePerUnit_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ratePerUnit_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratePerUnit_textActionPerformed(evt);
            }
        });

        Spannel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        sType.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sType.setText("Supplier's Type :");

        type_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "National", "International" }));
        type_combo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        type_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_comboActionPerformed(evt);
            }
        });

        SInfo_label.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        SInfo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user.png"))); // NOI18N
        SInfo_label.setText("Supplier's Info:");

        sName_label.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sName_label.setText("Supplier's Name :");

        SupName_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        SupName_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupName_textActionPerformed(evt);
            }
        });

        supEmailText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        supEmailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supEmailTextActionPerformed(evt);
            }
        });

        SupContact_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        SupContact_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupContact_textActionPerformed(evt);
            }
        });

        sEmail_label.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sEmail_label.setText("Supplier's Email :");

        sContact_label.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sContact_label.setText("Supplier's Contact :");

        javax.swing.GroupLayout SpannelLayout = new javax.swing.GroupLayout(Spannel);
        Spannel.setLayout(SpannelLayout);
        SpannelLayout.setHorizontalGroup(
            SpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SpannelLayout.createSequentialGroup()
                .addGroup(SpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SpannelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(SpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(sContact_label, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sType, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sName_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SpannelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sEmail_label, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(SpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(supEmailText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SupContact_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SupName_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
            .addGroup(SpannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SInfo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SpannelLayout.setVerticalGroup(
            SpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpannelLayout.createSequentialGroup()
                .addComponent(SInfo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(SpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sName_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SupName_text, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sEmail_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupContact_text, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sContact_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(SpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        remove_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        remove_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/remove.png"))); // NOI18N
        remove_button.setText("REMOVE ALL");
        remove_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        remove_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        remove_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_buttonActionPerformed(evt);
            }
        });

        add_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        add_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ok.png"))); // NOI18N
        add_button.setText("ADD PRODUCT");
        add_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        add_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FullPannelLayout = new javax.swing.GroupLayout(FullPannel);
        FullPannel.setLayout(FullPannelLayout);
        FullPannelLayout.setHorizontalGroup(
            FullPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FullPannelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(FullPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FullPannelLayout.createSequentialGroup()
                        .addGroup(FullPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pcode_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(productcode_text, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                        .addGap(87, 87, 87)
                        .addGroup(FullPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(productname_text, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(pname_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(FullPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qunatity_text, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantity_label, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(FullPannelLayout.createSequentialGroup()
                        .addGroup(FullPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ratePerUnit_text, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ratePerUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(FullPannelLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(FullPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(remove_button, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Spannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82))
        );
        FullPannelLayout.setVerticalGroup(
            FullPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FullPannelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(FullPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantity_label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pname_label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pcode_label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FullPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qunatity_text, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productname_text, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productcode_text, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(FullPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FullPannelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(ratePerUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ratePerUnit_text, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(add_button)
                        .addGap(18, 18, 18)
                        .addComponent(remove_button)
                        .addContainerGap(57, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FullPannelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Spannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        getContentPane().add(FullPannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void SupContact_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupContact_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupContact_textActionPerformed

    private void supEmailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supEmailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supEmailTextActionPerformed

    private void SupName_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupName_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupName_textActionPerformed

    private void type_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_comboActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_type_comboActionPerformed

    private void ratePerUnit_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratePerUnit_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ratePerUnit_textActionPerformed

    private void qunatity_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qunatity_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qunatity_textActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        // TODO add your handling code here:                                            
                                          
    // Retrieve text from all the fields
    String productCode = productcode_text.getText();
    String productName = productname_text.getText();
    String quantity = qunatity_text.getText();
    String rate = ratePerUnit_text.getText();
    String supplierName = SupName_text.getText();
    String supplierEmail = supEmailText.getText();
    String supplierContact = SupContact_text.getText();
    String supplierType = (String) type_combo.getSelectedItem();

    // Check if any field is empty
    if (productCode.isEmpty() || productName.isEmpty() || quantity.isEmpty() || rate.isEmpty() ||
        supplierName.isEmpty() || supplierEmail.isEmpty() || supplierContact.isEmpty()) {
        
        // Show a popup message
        JOptionPane.showMessageDialog(this, "Please fill all the fields!", "Incomplete Form", JOptionPane.WARNING_MESSAGE);
        
    } else {
        Connection con=null;
        PreparedStatement pst=null;
        // Proceed with adding the product to the database
        try {
            // Database connection code here
            con = connectDatabase();
            String sql = "INSERT INTO products (productCode, productName, quantity, rate, supplierName, supplierEmail, supplierContact, supplierType) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            pst = con.prepareStatement(sql);

            // Set the values from text fields to the SQL query
            pst.setInt(1, Integer.parseInt(productCode));
            pst.setString(2, productName);
            pst.setInt(3, Integer.parseInt(quantity));
            pst.setFloat(4, Float.parseFloat(rate));
            pst.setString(5, supplierName);
            pst.setString(6, supplierEmail);
            pst.setString(7, supplierContact);
            pst.setString(8, supplierType);

            // Execute the insert command
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Product added successfully!");

            // Clear the text fields after insertion
            productcode_text.setText("");
            productname_text.setText("");
            qunatity_text.setText("");
            ratePerUnit_text.setText("");
            SupName_text.setText("");
            supEmailText.setText("");
            SupContact_text.setText("");


        } catch (NumberFormatException ex) {
            // Show error message for wrong data type
            JOptionPane.showMessageDialog(this, "Wrong data entered. Please check the fields!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error. Please check the fields and try again!", "Database Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Close the resources
            try {
                if (pst != null) pst.close();
                if (con != null) con.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error closing the database connection", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }                             
    }//GEN-LAST:event_add_buttonActionPerformed

    private void remove_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_buttonActionPerformed
        // TODO add your handling code here:
                    productcode_text.setText("");
            productname_text.setText("");
            qunatity_text.setText("");
            ratePerUnit_text.setText("");
            SupName_text.setText("");
            supEmailText.setText("");
            SupContact_text.setText("");

    }//GEN-LAST:event_remove_buttonActionPerformed


    // Database connection method
    private Connection connectDatabase() {
        String url = "jdbc:mysql://localhost:3306/godamdb"; // Database URL
        String user = "root"; // Database username
        String password = "lamakhu"; // Database password
        
        try {
            return DriverManager.getConnection(url, user, password);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Failed to connect to the database", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FullPannel;
    private javax.swing.JLabel SInfo_label;
    private javax.swing.JPanel Spannel;
    private javax.swing.JTextField SupContact_text;
    private javax.swing.JTextField SupName_text;
    private javax.swing.JButton add_button;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel pcode_label;
    private javax.swing.JLabel pname_label;
    private javax.swing.JTextField productcode_text;
    private javax.swing.JTextField productname_text;
    private javax.swing.JLabel quantity_label;
    private javax.swing.JTextField qunatity_text;
    private javax.swing.JLabel ratePerUnit;
    private javax.swing.JTextField ratePerUnit_text;
    private javax.swing.JButton remove_button;
    private javax.swing.JLabel sContact_label;
    private javax.swing.JLabel sEmail_label;
    private javax.swing.JLabel sName_label;
    private javax.swing.JLabel sType;
    private javax.swing.JTextField supEmailText;
    private javax.swing.JComboBox<String> type_combo;
    // End of variables declaration//GEN-END:variables
}
